#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    rm -f /etc/certimanager/terminal.conf
    rmdir /etc/certimanager 2>/dev/null || true
    if [ -e /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
        db_purge || true
    fi
fi

exit 0
